In [1]:
# First let us import all the different libraries that we need
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.metrics

#### Looking at the dataframe
Let us look at the dataframe for a little bit of insight into the data

In [2]:
# Readinbg the file 
df = pd.read_csv(r"G:\Hemant_Data\DBDA_Project\flight_data\Merged_Flight_Weather.csv", index_col = 0)
df.head()

,index_x,ArrDel15,ArrDelayMinutes,ArrTime,CRSArrTime,CRSDepTime,DayofMonth,DepDel15,DepDelayMinutes,DepTime,...,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity,time,date,airport
0,0,0.0,8.0,1610.0,1602,745,1,0.0,0.0,741.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA
1,12608,1.0,33.0,1237.0,1204,820,1,0.0,1.0,821.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA
2,50768,0.0,0.0,1138.0,1143,759,1,0.0,0.0,754.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA
3,51023,0.0,10.0,1401.0,1351,738,1,0.0,2.0,740.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA
4,61167,0.0,0.0,1524.0,1527,745,1,0.0,0.0,742.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA

In [3]:
df.columns

Index(['index_x', 'ArrDel15', 'ArrDelayMinutes', 'ArrTime', 'CRSArrTime',
       'CRSDepTime', 'DayofMonth', 'DepDel15', 'DepDelayMinutes', 'DepTime',
       'Dest', 'DestAirportID', 'FlightDate', 'UniqueCarrier', 'AirlineID',
       'Month', 'Origin', 'OriginAirportID', 'Quarter', 'Year', 'DeptTime',
       'index_y', 'windspeedKmph', 'winddirDegree', 'weatherCode', 'precipMM',
       'visibility', 'pressure', 'cloudcover', 'DewPointF', 'WindGustKmph',
       'tempF', 'WindChillF', 'humidity', 'time', 'date', 'airport'],
      dtype='object')

In [4]:
# Now the shape of the dataframe
df.shape

(1851094, 37)

In [5]:
# Check for missing values
df.isna().sum()

index_x            0
ArrDel15           0
ArrDelayMinutes    0
ArrTime            0
CRSArrTime         0
CRSDepTime         0
DayofMonth         0
DepDel15           0
DepDelayMinutes    0
DepTime            0
Dest               0
DestAirportID      0
FlightDate         0
UniqueCarrier      0
AirlineID          0
Month              0
Origin             0
OriginAirportID    0
Quarter            0
Year               0
DeptTime           0
index_y            0
windspeedKmph      0
winddirDegree      0
weatherCode        0
precipMM           0
visibility         0
pressure           0
cloudcover         0
DewPointF          0
WindGustKmph       0
tempF              0
WindChillF         0
humidity           0
time               0
date               0
airport            0
dtype: int64

In [6]:
df.columns

Index(['index_x', 'ArrDel15', 'ArrDelayMinutes', 'ArrTime', 'CRSArrTime',
       'CRSDepTime', 'DayofMonth', 'DepDel15', 'DepDelayMinutes', 'DepTime',
       'Dest', 'DestAirportID', 'FlightDate', 'UniqueCarrier', 'AirlineID',
       'Month', 'Origin', 'OriginAirportID', 'Quarter', 'Year', 'DeptTime',
       'index_y', 'windspeedKmph', 'winddirDegree', 'weatherCode', 'precipMM',
       'visibility', 'pressure', 'cloudcover', 'DewPointF', 'WindGustKmph',
       'tempF', 'WindChillF', 'humidity', 'time', 'date', 'airport'],
      dtype='object')

In [7]:
# Here we drop all the columns we don't need for our classification
df = df.drop(columns=['index_x', 'time', 'date', 'FlightDate', 'index_y', 'DeptTime','ArrDelayMinutes','DepDel15',
                      'DepDelayMinutes','ArrTime','DepTime','OriginAirportID','DestAirportID','DeptTime','weatherCode',
                      'airport','AirlineID'])
df.head()

,ArrDel15,CRSArrTime,CRSDepTime,DayofMonth,Dest,UniqueCarrier,Month,Origin,Quarter,Year,...,winddirDegree,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity
0,0.0,1602,745,1,JFK,AA,1,SEA,1,2016,...,108,0.0,10,1030,0,23,8,34,29,65
1,1.0,1204,820,1,PHX,AA,1,SEA,1,2016,...,108,0.0,10,1030,0,23,8,34,29,65
2,0.0,1143,759,1,DEN,UA,1,SEA,1,2016,...,108,0.0,10,1030,0,23,8,34,29,65
3,0.0,1351,738,1,IAH,UA,1,SEA,1,2016,...,108,0.0,10,1030,0,23,8,34,29,65
4,0.0,1527,745,1,ATL,DL,1,SEA,1,2016,...,108,0.0,10,1030,0,23,8,34,29,65

In [8]:
df.columns

Index(['ArrDel15', 'CRSArrTime', 'CRSDepTime', 'DayofMonth', 'Dest',
       'UniqueCarrier', 'Month', 'Origin', 'Quarter', 'Year', 'windspeedKmph',
       'winddirDegree', 'precipMM', 'visibility', 'pressure', 'cloudcover',
       'DewPointF', 'WindGustKmph', 'tempF', 'WindChillF', 'humidity'],
      dtype='object')

In [9]:
df

,ArrDel15,CRSArrTime,CRSDepTime,DayofMonth,Dest,UniqueCarrier,Month,Origin,Quarter,Year,...,winddirDegree,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity
0,0.0,1602,745,1,JFK,AA,1,SEA,1,2016,...,108,0.0,10,1030,0,23,8,34,29,65
1,1.0,1204,820,1,PHX,AA,1,SEA,1,2016,...,108,0.0,10,1030,0,23,8,34,29,65
2,0.0,1143,759,1,DEN,UA,1,SEA,1,2016,...,108,0.0,10,1030,0,23,8,34,29,65
3,0.0,1351,738,1,IAH,UA,1,SEA,1,2016,...,108,0.0,10,1030,0,23,8,34,29,65
4,0.0,1527,745,1,ATL,DL,1,SEA,1,2016,...,108,0.0,10,1030,0,23,8,34,29,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1851089,1.0,1859,1424,17,EWR,UA,12,IAH,4,2017,...,91,0.0,10,1019,88,50,7,59,59,74
1851090,0.0,1733,1300,17,EWR,UA,12,IAH,4,2017,...,77,0.0,10,1020,84,50,8,57,57,77
1851091,0.0,1433,1304,17,DEN,UA,12,IAH,4,2017,...,77,0.0,10,1020,84,50,8,57,57,77
1851092,0.0,8,2100,17,MIA,UA,12,EWR,4,2017,...,123,0.0,10,1024,100,28,16,32,29,88
1851093,0.0,208,2322,17,SFO,UA,12,ORD,4,2017,...,219,0.0,6,1016,100,34,12,37,34,90

In [10]:
# Looking at the new features
df.columns

Index(['ArrDel15', 'CRSArrTime', 'CRSDepTime', 'DayofMonth', 'Dest',
       'UniqueCarrier', 'Month', 'Origin', 'Quarter', 'Year', 'windspeedKmph',
       'winddirDegree', 'precipMM', 'visibility', 'pressure', 'cloudcover',
       'DewPointF', 'WindGustKmph', 'tempF', 'WindChillF', 'humidity'],
      dtype='object')

In [11]:
from sklearn import preprocessing

In [12]:
le = preprocessing.LabelEncoder()

In [13]:
c = df.Origin.astype('category')

In [14]:
d = dict(enumerate(c.cat.categories))
print (d)

{0: 'ATL', 1: 'CLT', 2: 'DEN', 3: 'DFW', 4: 'EWR', 5: 'IAH', 6: 'JFK', 7: 'LAS', 8: 'LAX', 9: 'MCO', 10: 'MIA', 11: 'ORD', 12: 'PHX', 13: 'SEA', 14: 'SFO'}

In [15]:
df.shape

(1851091, 20)

In [16]:
df.duplicated().sum()

1700

In [17]:
df.drop_duplicates(inplace=True)
df.shape

(1849391, 20)

In [18]:
df['Origin']

0          SEA
1          SEA
2          SEA
3          SEA
4          SEA
          ...
1851086    IAH
1851087    IAH
1851088    IAH
1851089    EWR
1851090    ORD
Name: Origin, Length: 1849391, dtype: object

### Label Encoding using cat.codes
Label Encoding refers to converting the labels into numeric form so as to convert it into the machine-readable form. Machine learning algorithms can then decide in a better way on how those labels must be operated. It is an important pre-processing step for the structured dataset in supervised learning.
Here we are label encoding the `Origin` and the `airport` features, by first converting them to category type and then using `cat.codes`

In [19]:
df.dtypes

ArrDel15         float64
CRSArrTime         int64
CRSDepTime         int64
DayofMonth         int64
Dest              object
Month              int64
Origin            object
Quarter            int64
Year               int64
windspeedKmph      int64
winddirDegree      int64
precipMM         float64
visibility         int64
pressure           int64
cloudcover         int64
DewPointF          int64
WindGustKmph       int64
tempF              int64
WindChillF         int64
humidity           int64
dtype: object

In [12]:
df["Origin"] = df["Origin"].astype('category')
df["Dest"] = df["Dest"].astype('category')
df["UniqueCarrier"] = df["UniqueCarrier"].astype('category')
# To see if our features have convered to category
df.dtypes

ArrDel15          float64
CRSArrTime          int64
CRSDepTime          int64
DayofMonth          int64
Dest             category
UniqueCarrier    category
Month               int64
Origin           category
Quarter             int64
Year                int64
windspeedKmph       int64
winddirDegree       int64
precipMM          float64
visibility          int64
pressure            int64
cloudcover          int64
DewPointF           int64
WindGustKmph        int64
tempF               int64
WindChillF          int64
humidity            int64
dtype: object

As you can see those both Origin and airport have been converted into category type

In [15]:
df["Origin"] = df["Origin"].cat.codes
df["Dest"] = df["Dest"].cat.codes
df["UniqueCarrier"] = df["UniqueCarrier"].cat.codes
df.head()

AttributeError: Can only use .cat accessor with a 'category' dtype

In [16]:
df.dtypes

ArrDel15         float64
CRSArrTime         int64
CRSDepTime         int64
DayofMonth         int64
Dest                int8
UniqueCarrier       int8
Month              int64
Origin              int8
Quarter            int64
Year               int64
windspeedKmph      int64
winddirDegree      int64
precipMM         float64
visibility         int64
pressure           int64
cloudcover         int64
DewPointF          int64
WindGustKmph       int64
tempF              int64
WindChillF         int64
humidity           int64
dtype: object

In [15]:
df.Origin.value_counts()

8     209321
14    166932
11    153438
0     146723
2     144149
7     132154
3     125904
13    115707
12    114012
4     100170
9      99568
6      93436
5      89551
1      83486
10     76540
Name: Origin, dtype: int64

In [17]:
df.columns

Index(['ArrDel15', 'CRSArrTime', 'CRSDepTime', 'DayofMonth', 'Dest', 'Month',
       'Origin', 'Quarter', 'Year', 'windspeedKmph', 'winddirDegree',
       'precipMM', 'visibility', 'pressure', 'cloudcover', 'DewPointF',
       'WindGustKmph', 'tempF', 'WindChillF', 'humidity'],
      dtype='object')

In [ ]:
df

In [ ]:
df['Origin']

In [17]:
X = df.drop(columns = ['ArrDel15'])
y = df['ArrDel15']

# Spplitting the datasets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,stratify=y,random_state=2022)

In [18]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1295765, 20), (555329, 20), (1295765,), (555329,))

## Accuracy measurement
There are also a few metrics that we use for checking the accuracy of our model. Some of them are
1. model.score()
2. A classification report that gives us the precision and the recall and also the F1 score, where:
    1. Precision is the fraction of how many of the items that are selected are relevant.
    2. Recall is the fraction of how many relevant items are selected.
    3. F1 score which is the harmonic mean between the Precision and the Recall
3. A confusion matrix which gives us a matrix of the true negatives($C_{0, 0}$), false negatives($C_{1, 0}$), true positives($C_{0, 1}$) false positives($C_{1, 1}$)

In [19]:
import sklearn.metrics

## XGBoost Classifier
XGBoost is a decision-tree-based ensemble Machine Learning algorithm that uses a gradient boosting framework

In [20]:
import xgboost
from xgboost import XGBClassifier

C:\Users\kruna\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [21]:
xgboost_model = XGBClassifier()
xbgoost_classifier_unsampled = xgboost_model.fit(X_train, y_train)

C:\Users\kruna\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\kruna\anaconda3\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[14:37:40] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [22]:
y_pred_xgboost = xgboost_model.predict(X_test)

In [23]:
print("XGBoost Clasifier Train Accuracy : {} %".format(xbgoost_classifier_unsampled.score(X_train, y_train)*100))
print("\nXGBoost Trees Clasifier Test Accuracy : {} %".format(sklearn.metrics.accuracy_score(y_test, y_pred_xgboost)*100))
print("-------------------------------------------------------------------------------------------------")
print("\nClassification Report : \n {}".format(sklearn.metrics.classification_report(y_test, y_pred_xgboost)))
print("-------------------------------------------------------------------------------------------------")
print("\n Confusion Matrix :- \n{}".format(sklearn.metrics.confusion_matrix(y_test, y_pred_xgboost)))

XGBoost Clasifier Train Accuracy : 80.60744039235509 %

XGBoost Trees Clasifier Test Accuracy : 80.21785284038832 %
-------------------------------------------------------------------------------------------------

Classification Report :
               precision    recall  f1-score   support

         0.0       0.81      0.98      0.89    438929
         1.0       0.64      0.13      0.21    116400

    accuracy                           0.80    555329
   macro avg       0.73      0.55      0.55    555329
weighted avg       0.77      0.80      0.74    555329

-------------------------------------------------------------------------------------------------

 Confusion Matrix :-
[[430900   8029]
 [101827  14573]]

In [45]:
import pickle

In [48]:
## Save the model to disk
pickle_out = open('classificationModify.pkl','wb')
pickle.dump(xgboost_model,pickle_out)

In [49]:
loaded_model = pickle.load(open('classificationModify.pkl','rb'))
cols_when_model_builds = loaded_model.get_booster().feature_names
#result = loaded_model.score(X_test,y_test)
#print(result)
cols_when_model_builds

['CRSArrTime',
 'CRSDepTime',
 'DayofMonth',
 'Dest',
 'UniqueCarrier',
 'Month',
 'Origin',
 'Quarter',
 'Year',
 'windspeedKmph',
 'winddirDegree',
 'precipMM',
 'visibility',
 'pressure',
 'cloudcover',
 'DewPointF',
 'WindGustKmph',
 'tempF',
 'WindChillF',
 'humidity']

In [50]:
result = loaded_model.score(X_test,y_test)
print(result)

0.8021785284038832

In [56]:
# save to csv
df.to_csv('D:\krunal_data\project\IACSD_Project\ModelBuilding\Rough\Modify.csv')

## Testing on Unlabelled data

In [34]:
# Readinbg the file 
tst_df = pd.read_csv(r"G:\Hemant_Data\DBDA_Project\flight_data\Merged_Flight_Weather.csv", index_col = 0,nrows=1000)
tst_df.head()

,index_x,ArrDel15,ArrDelayMinutes,ArrTime,CRSArrTime,CRSDepTime,DayofMonth,DepDel15,DepDelayMinutes,DepTime,...,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity,time,date,airport
0,0,0.0,8.0,1610.0,1602,745,1,0.0,0.0,741.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA
1,12608,1.0,33.0,1237.0,1204,820,1,0.0,1.0,821.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA
2,50768,0.0,0.0,1138.0,1143,759,1,0.0,0.0,754.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA
3,51023,0.0,10.0,1401.0,1351,738,1,0.0,2.0,740.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA
4,61167,0.0,0.0,1524.0,1527,745,1,0.0,0.0,742.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA

In [35]:
tst_df.shape

(1000, 37)

In [36]:
tst_df['ArrDel15']==1

0      False
1       True
2      False
3      False
4      False
       ...
995    False
996    False
997     True
998    False
999    False
Name: ArrDel15, Length: 1000, dtype: bool

In [37]:
tst_df.columns

Index(['index_x', 'ArrDel15', 'ArrDelayMinutes', 'ArrTime', 'CRSArrTime',
       'CRSDepTime', 'DayofMonth', 'DepDel15', 'DepDelayMinutes', 'DepTime',
       'Dest', 'DestAirportID', 'FlightDate', 'UniqueCarrier', 'AirlineID',
       'Month', 'Origin', 'OriginAirportID', 'Quarter', 'Year', 'DeptTime',
       'index_y', 'windspeedKmph', 'winddirDegree', 'weatherCode', 'precipMM',
       'visibility', 'pressure', 'cloudcover', 'DewPointF', 'WindGustKmph',
       'tempF', 'WindChillF', 'humidity', 'time', 'date', 'airport'],
      dtype='object')

In [38]:
# Here we drop all the columns we don't need for our classification
tst_df = tst_df.drop(columns=['index_x', 'time', 'date', 'FlightDate', 'index_y', 'DeptTime','DepDel15','ArrDelayMinutes',
                      'DepDelayMinutes','ArrTime','DepTime','OriginAirportID','DestAirportID','DeptTime','weatherCode',
                      'airport','ArrDel15','AirlineID'])

In [39]:
tst_df.columns

Index(['CRSArrTime', 'CRSDepTime', 'DayofMonth', 'Dest', 'UniqueCarrier',
       'Month', 'Origin', 'Quarter', 'Year', 'windspeedKmph', 'winddirDegree',
       'precipMM', 'visibility', 'pressure', 'cloudcover', 'DewPointF',
       'WindGustKmph', 'tempF', 'WindChillF', 'humidity'],
      dtype='object')

In [40]:
tst_df

,CRSArrTime,CRSDepTime,DayofMonth,Dest,UniqueCarrier,Month,Origin,Quarter,Year,windspeedKmph,winddirDegree,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity
0,1602,745,1,JFK,AA,1,SEA,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65
1,1204,820,1,PHX,AA,1,SEA,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65
2,1143,759,1,DEN,UA,1,SEA,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65
3,1351,738,1,IAH,UA,1,SEA,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65
4,1527,745,1,ATL,DL,1,SEA,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1231,1120,30,SFO,AA,1,PHX,1,2016,6,103,0.0,10,1016,0,22,9,62,63,44
996,1138,1105,30,LAX,AA,1,PHX,1,2016,6,103,0.0,10,1016,0,22,9,62,63,44
997,1128,1115,30,LAS,AA,1,PHX,1,2016,6,103,0.0,10,1016,0,22,9,62,63,44
998,1658,1105,30,CLT,AA,1,PHX,1,2016,6,103,0.0,10,1016,0,22,9,62,63,44
999,1510,1035,30,ORD,F9,1,PHX,1,2016,6,103,0.0,10,1016,0,22,9,62,63,44

In [41]:
tst_df["Origin"] = tst_df["Origin"].astype('category')
tst_df["Dest"] = tst_df["Dest"].astype('category')
tst_df["UniqueCarrier"] = tst_df["UniqueCarrier"].astype('category')

In [42]:
tst_df["Origin"] = tst_df["Origin"].cat.codes
tst_df["Dest"] = tst_df["Dest"].cat.codes
tst_df["UniqueCarrier"] = tst_df["UniqueCarrier"].cat.codes
tst_df.head()

,CRSArrTime,CRSDepTime,DayofMonth,Dest,UniqueCarrier,Month,Origin,Quarter,Year,windspeedKmph,winddirDegree,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity
0,1602,745,1,6,0,1,2,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65
1,1204,820,1,12,0,1,2,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65
2,1143,759,1,2,6,1,2,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65
3,1351,738,1,5,6,1,2,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65
4,1527,745,1,0,3,1,2,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65

In [43]:
predictions = xgboost_model.predict(tst_df)

C:\Users\kruna\anaconda3\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

In [44]:
print(predictions)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [101]:
# Readinbg the file 
tst_df = pd.read_csv("D:\krunal_data\project\IACSD_Project\Merged_Flight_Weather.csv", index_col = 0,nrows=1)
tst_df.head()

,index_x,ArrDel15,ArrDelayMinutes,ArrTime,CRSArrTime,CRSDepTime,DayofMonth,DepDel15,DepDelayMinutes,DepTime,...,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity,time,date,airport
0,0,0.0,8.0,1610.0,1602,745,1,0.0,0.0,741.0,...,1030,0,23,8,34,29,65,800,2016-01-01,SEA

In [102]:
tst_df = tst_df.drop(columns=['index_x', 'time', 'date', 'FlightDate', 'index_y', 'DeptTime','DepDel15','ArrDelayMinutes',
                      'DepDelayMinutes','ArrTime','DepTime','OriginAirportID','DestAirportID','DeptTime','weatherCode',
                      'airport','ArrDel15'])

In [103]:
tst_df["Origin"] = tst_df["Origin"].astype('category')
tst_df["Dest"] = tst_df["Dest"].astype('category')
tst_df["Origin"] = tst_df["Origin"].cat.codes
tst_df["Dest"] = tst_df["Dest"].cat.codes
tst_df.head()

,CRSArrTime,CRSDepTime,DayofMonth,Dest,Month,Origin,Quarter,Year,windspeedKmph,winddirDegree,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity
0,1602,745,1,0,1,0,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65

In [105]:
tst_df

,CRSArrTime,CRSDepTime,DayofMonth,Dest,Month,Origin,Quarter,Year,windspeedKmph,winddirDegree,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity
0,1602,745,1,0,1,0,1,2016,7,108,0.0,10,1030,0,23,8,34,29,65

In [104]:
loaded_model = pickle.load(open('classificationModify.pkl','rb'))
result =loaded_model.predict(tst_df)
print(result)

[0]